### ISSUE TITLE
Continuous Integration (CI)

### ISSUE THREAD

**Issue by HenrikBengtsson** [olshena/babel#4]
Go to and sign up using your GitHub account at the following services:
- https://travis-ci.org/
  - Then go to https://travis-ci.org/profile and enable `olshena/babel`
- https://ci.appveyor.com/
  - Then go to https://ci.appveyor.com/projects/new and enable `olshena/babel`
- https://codecov.io/

unless you've already done so in the past.

**Comment by HenrikBengtsson** [comment]
When you've done this, I can add the required config files to the repository such that they'll run automatic tests on Linux, OS X, and Windows (on previous, current and devel versions of R) as well as providing you with code coverage online reports.  All this will be fully automatic (with every `git push`).

**Comment by olshena** [comment]
Appveyor looks right.  travis I tried to do but does not appear to have
worked.  codecov created an account but not sure what to do past that.

**Comment by HenrikBengtsson** [comment]
Keep search for info online, because it should work and it wasn't hard for
me when I first set it up. The repositories must be public though -private
doesn't work.

**Comment by olshena** [comment]
It is private.  It says that private is okay, but then it does not work.

**Comment by olshena** [comment]
I found that .org is for public libraries and .com is for private libraries
but they look the same.

**Comment by olshena** [comment]
babel is public.

**Comment by HenrikBengtsson** [comment]
Private is not OK. You have to pay.

Henrik

**Comment by olshena** [comment]
trevor build is supposed to be triggered by a commit.  Is this to the
master or the develop branch?

**Comment by HenrikBengtsson** [comment]
I'll fix /trigger the build when I get to a computer. I just needed you to
enable everything first.

Henrik
On Jun 19, 2016 9:21 PM, "Adam Olshen" notifications@github.com wrote:

trevor build is supposed to be triggered by a commit. Is this to the
master or the develop branch?

On Sun, Jun 19, 2016 at 9:00 PM, Henrik Bengtsson notifications@github.com
wrote:

> Private is not OK. You have to pay.
> 
> Henrik
> On Jun 19, 2016 20:26, "Adam Olshen" notifications@github.com wrote:
> 
> > It is private. It says that private is okay, but then it does not work.
> > 
> > On Sun, Jun 19, 2016 at 8:16 PM, Henrik Bengtsson <
> > notifications@github.com>
> > wrote:
> > 
> > > Keep search for info online, because it should work and it wasn't hard
> > > for
> > > me when I first set it up. The repositories must be public though
> > > -private
> > > doesn't work.
> > > On Jun 19, 2016 20:08, "Adam Olshen" notifications@github.com wrote:
> > > 
> > > > Appveyor looks right. travis I tried to do but does not appear to
> > > > have
> > > > worked. codecov created an account but not sure what to do past
> > > > that.
> > > > 
> > > > On Sat, Jun 18, 2016 at 7:38 PM, Henrik Bengtsson <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > When you've done this, I can add the required config files to the
> > > > > repository such that they'll run automatic tests on Linux, OS X,
> > > > > and
> > > > > Windows (on previous, current and devel versions of R) as well as
> > > > > providing
> > > > > you with code coverage online reports. All this will be fully
> > > > > automatic
> > > > > (with every git push).
> > > > > 
> > > > > —
> > > > > You are receiving this because you were assigned.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <https://github.com/olshena/babel/issues/4#issuecomment-226975974
> > > > > ,
> > > > > or
> > > > > mute
> > > > > the thread
> > > > > <
> 
> https://github.com/notifications/unsubscribe/AHo1gcsv5GjyQU6QRwCQ-k1g801x9Tvaks5qNKuqgaJpZM4I5E2c
> 
> > > > > .
> > > > 
> > > > —
> > > > You are receiving this because you were assigned.
> > > > Reply to this email directly, view it on GitHub
> > > > https://github.com/olshena/babel/issues/4#issuecomment-227041702,
> > > > or
> > > > mute
> > > > the thread
> > > > <
> 
> https://github.com/notifications/unsubscribe/ABir0sUTO8xLreFL9dkswRRy6zbM9oiYks5qNgP4gaJpZM4I5E2c
> 
> > > > .
> > > 
> > > —
> > > You are receiving this because you were assigned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/olshena/babel/issues/4#issuecomment-227042439, or
> > > mute
> > > the thread
> > > <
> 
> https://github.com/notifications/unsubscribe/AHo1gdaNz1hex_tNyQEKFw7gWmfB4TBDks5qNgYGgaJpZM4I5E2c
> 
> > > .
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/olshena/babel/issues/4#issuecomment-227043244, or
> > mute
> > the thread
> > <
> 
> https://github.com/notifications/unsubscribe/ABir0oGDowrfggqry8rI4z82TuDk7yl4ks5qNghLgaJpZM4I5E2c
> 
> > .
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/olshena/babel/issues/4#issuecomment-227046072, or
> mute
> the thread
> <
> https://github.com/notifications/unsubscribe/AHo1gQmeG-6M5nn3yGBhIXpux_AZjZv_ks5qNhBXgaJpZM4I5E2c
> 
> .

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
https://github.com/olshena/babel/issues/4#issuecomment-227047638, or mute
the thread
https://github.com/notifications/unsubscribe/ABir0hq6kA2yd9EeS3W7AvXi86GivWz0ks5qNhUbgaJpZM4I5E2c
.

**Comment by olshena** [comment]
I have enabled the babel package. I think I am ready.

**Comment by olshena** [comment]
I am getting build failed errors, which I think is a good sign that babel
is enabled.

**Comment by olshena** [comment]
Build failed errors on appveyor as well as trevor.

**Comment by HenrikBengtsson** [comment]
For the `develop` branch:
I've added `.travis.yml` and `appveyor.yml` which now triggers proper builds and checks on the package.  I've also added a `README.md` with links to these sites.

As you can see, Travis CI reports the checks as "error", which is because there are WARNINGs during `R CMD check --as-cran`.   Fix those and all the other NOTEs.   

Note, this is for `develop` branch for now, so make sure to check that branch out and work with that.  Any **pushes** (you can have multiple commits per push) you'll do will trigger a new run on the CIs.  (If you just want to push without trigger this, add `[ci skip]` anywhere in the commit message, as I did for the README file).

When you've got the develop branch fixed, we can look at the master branch.

**Comment by HenrikBengtsson** [comment]
Forgot to say, the Codecov analysis will only run if the Travis CI succeeds, i.e. no ERRORs or WARNINGs during `R CMD check`.

**Comment by olshena** [comment]
Currently stuck because my machine cannot build the vignettes:

PSG-0CUF9VN-DT:Code olshena$ R CMD build babel
- checking for file ‘babel/DESCRIPTION’ ... OK
- preparing ‘babel’:
- checking DESCRIPTION meta-information ... OK
- installing the package to build vignettes
- creating vignettes ... ERROR

Warning in parseRepos(sets = repos, where = where, fallback = fallback,  :

  Had to fall back to a set of predefined repositories (please make sure to
set your package repositories properly, cf. ?setRepositories): CRAN: ‘@CRAN@’
-> ‘http://cran.r-project.org’

Loading required package: edgeR

Loading required package: limma

Error: processing vignette 'babel.tex.rsp' failed with diagnostics:

Running 'texi2dvi' on 'babel.tex' failed.

Execution halted

On Sun, Jun 19, 2016 at 10:35 PM, Henrik Bengtsson <notifications@github.com

**Comment by olshena** [comment]
Should be fixed with installation of mactex that will be done in person on
Monday.

**Comment by olshena** [comment]
Now no errors or warnings.

On Sun, Jun 19, 2016 at 10:35 PM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
Great. And now you see that Travis CI does codecov analysis at the end and uploads to the results to codecov.io.  Since you have no package tests, there is zero coverage, cf. https://codecov.io/gh/olshena/babel/branch/develop.

Closing this one.
